#!/bin/bash

_git_a() {
	_git_add
}

_git_aliases() {
	return
}

_git_authors() {
	__gitcomp "-l -v"
}

_git_branch_remote() {
	__gitcomp "$(git list-branches)"
}

_git_cdiff() {
	_git_diff
}

_git_changelog() {
	return
}

_git_ci() {
	_git_commit
}

_git_co() {
	_git_checkout
}

_git_cob() {
	_git_checkout
}

_git_commands() {
	__gitcomp "$(grep -iE --colour=never '^git' /var/git/local/commands|cut -d' ' -f2)"
}

_git_committers() {
	__gitcomp "-l -v"
}

_git_cpush() {
	if [[ "$cword" < "3" ]];then
		__gitcomp "$(git remote)"
	else
		_git_branch_remote
	fi
}

_git_current_branch() {
	return
}

_git_detach() {
	return
}

_git_fastforward() {
	_git_branch_remote
}

_git_ff() {
	_git_fastforward
}

_git_fpush() {
	_git_cpush
}

_git_hoist() {
	if [[ "$cword" < "3" ]];then
		_git_branch_remote
	else
		__gitcomp "$( __git_refs)"
	fi
}

_git_ignore() {
	return
}

_git_ignored() {
	return
}

_git_lg() {
	_git_log
}

_git_lga() {
	_git_log
}

_git_lgg() {
	_git_log
}

_git_lgnot() {
	__gitcomp "$(git show-ref|cut -d' ' -f2|sed -E 's/^refs\/(head|remote)s\///'|tr '\n' ' ')"
}

_git_lgo() {
	return
}

_git_lgs() {
	return
}

_git_list_branches() {
	#TODO
	return
}

_git_paths() {
	_git_remote
}

_git_rb() {
	_git_rebase
}

_git_release() {
	push=
	yes=
	suggest=

	for i in "$COMP_LINE";do
		case "$i" in
			-y)
				yes=1
				;;
			-p|--push)
				push=1
				;;
		esac
	done

	if [ -z "$push" ];then
		suggest+=" -p --push "
	fi

	if [ -z "$yes" ];then
		suggest+=" -y "
	fi

	num="$(((COMP_CWORD - 2 - $yes - $push)))"

	if [ "$num" == "0" ];then
		currentVersion=

		for tag in $(git tag -l | grep -P "^v([0-9]+(\.|(?=$))){3}$" | sort -rV);do
			if [ -z "$currentVersion" ] && git merge-base --is-ancestor "$tag" HEAD;then
				currentVersion="${tag:1}"
			fi
		done;

		if [ -z "$currentVersion" ];then
			currentVersion="0.0.0"
		fi

		major="${currentVersion%%.*}"
		majorRemaining="${currentVersion#*.}"
		minor="${majorRemaining%%.*}"
		minorRemaining="${majorRemaining#*.}"
		majorVersion="$(( $major + 1 )).0.0"
		minorVersion="$major.$(( $minor + 1 )).0"
		patchVersion="$major.$minor.$(( ${minorRemaining%%.*} + 1))"

		suggest+=" major minor patch v$majorVersion v$minorVersion v$patchVersion "
	fi

	__gitcomp "${suggest[*]}"
}

_git_reset_permissions() {
	return
}

_git_st() {
	_git_status
}

_git_subup() {
	__gitcomp "
		--remote --no-fetch
		--recommend-shallow --no-recommend-shallow
		--force --rebase --merge --reference --depth --jobs
	"
}

_git_tidy_branches() {
	return
}

_git_update() {
	return
}

_git_unstage() {
	_git_reset
}

_git_yoink() {
	_git_cherry_pick
}
