#!/bin/bash

_git_a() {
	_git_add
}

_git_branch_remote() {
	return
}

_git_cdiff() {
	_git_diff
}

_git_ci() {
	_git_commit
}

_git_co() {
	_git_checkout
}

_git_cob() {
	_git_checkout
}

_git_commands() {
	#TODO
	return
}

_git_current_branch() {
	#TODO
	return
}

_git_detach() {
	#TODO
	return
}

_git_fastforward() {
	return
}

_git_ff() {
	_git_fastforward
}

_git_hoist() {
	return
}

_git_lg() {
	_git_log
}

_git_lga() {
	_git_log
}

_git_lgg() {
	_git_log
}

_git_list_branches() {
	#TODO
	return
}

_git_paths() {
	_git_remote
}

_git_rb() {
	_git_rebase
}

_git_st() {
	_git_status
}

_git_subup() {
	__gitcomp "
		--remote --no-fetch
		--recommend-shallow --no-recommend-shallow
		--force --rebase --merge --reference --depth --jobs
	"	
}

_git_update() {
	return
}

_git_unstage() {
	_git_reset
}

_git_yoink() {
	_git_cherry_pick
}

