#!/bin/bash

function _confirm() {
	local variable="$1"
	shift
	local message="$1"
	shift
	# declare -n options=$1
	declare -a options_passed=("$@")
	declare -A options=()
	local options_var=""
	local key
	local reply

	for i in "${options_passed[@]}";do
		key="${i::1}"
		key="${key,,}"
		options["$key"]="${i:2}"
		options_var+="$key/"
	done

	while true;do
		read -p $'\e[94m'"$message [${options_var::-1}]?"$'\e[0m ' -r

		reply="${REPLY,,}"
		reply="${reply::1}"

		if [[ "${options["$reply"]}" ]];then
			eval $variable="'$reply'"
			return
		fi

		for i in "${!options[@]}";do
			echo $'\e[91m'"$i - ${options[$i]}"$'\e[0m '
		done
	done
}
